name: Build

on: 
  workflow_call:

env:
  name: "IBCore"

jobs: 
  test:
    name: Run Go Tests
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22]
        arch: [amd64, arm64]  # Add support for multiple architectures

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify Go installation
        run: go version

      - name: Run Go tests
        run: |
          export GOARCH=${{ matrix.arch }}
          go mod tidy
          go test ./... -v  # Run tests before building
        continue-on-error: false  # Make sure the job fails if tests fail
    
  build:
    needs: test
    name: Build Go binaries
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22]
        arch: [amd64, arm64]  # Add support for multiple architectures

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify Go installation
        run: go version

      - name: Build binary for ${{ matrix.arch }}
        run: |
          export GOARCH=${{ matrix.arch }}
          go mod tidy
          go build -v -buildmode=c-archive -o ${{ env.name }}-${{ matrix.os }}-${{ matrix.arch }}.a .

      - name: Move binaries to dist (Linux/macOS)
        run: |
          mkdir -p dist/
          mv ${{ env.name }}-${{ matrix.os }}-${{ matrix.arch }}.* dist/
        if: runner.os != 'Windows'

      - name: Move binaries to dist (Windows)
        run: |
          mkdir dist
          move ${{ env.name }}-${{ matrix.os }}-${{ matrix.arch }}.* dist\
        if: runner.os == 'Windows'

      - name: List output files (Linux/macOS)
        run: ls -lah dist/
        if: runner.os != 'Windows'

      - name: List output files (Windows)
        run: dir dist\
        if: runner.os == 'Windows'

      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}-${{ matrix.os }}-${{ matrix.arch }}.bin
          path: dist/
